POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVldHVoIiwiaWQiOiI1Y2FkODk1YmRkMzZjMDJiOTZlODIwYTgiLCJpYXQiOjE1NTQ5MDUyNjZ9.yywuU0PAHyWXpyCu2o3vkgSVY8peeAnclD9Oc3xv_4U

{
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "__v": 0
}